// Copyright 2022 QMK -- generated source code only, image retains original copyright
// SPDX-License-Identifier: GPL-2.0-or-later

// This file was auto-generated by `qmk painter-convert-graphics -i 90882a184302c5c6.png -f pal256`

#pragma once

#include <qp.h>

extern const uint32_t gfx_90882a184302c5c6_length;
extern const uint8_t  gfx_90882a184302c5c6[8610];
