# MCU name
MCU = MK20DX256
BOARD = IC_TEENSY_3_1

BOOTLOADER = halfkay

POINTING_DEVICE_ENABLE = yes
POINTING_DEVICE_DRIVER = pimoroni_trackball

QUANTUM_PAINTER_ENABLE = yes
QUANTUM_PAINTER_DRIVERS = st7789_spi
